# Decodelabs Data Analysis Project 1
---
## Workflow:
### 1- Add libraries 
### 2- Load Dataset
### 3- Clean Data 

---

## Step 1: Libraries

In [ ]:
import pandas as pd
import numpy as np

## Step 2: Load Dataset

In [5]:
# Load the data and read it 
df_dataset = pd.read_csv('Dataset/Dataset_for_Data_Analytics.csv')

df_dataset.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
# Shape of the dataset
df_dataset.shape

(1200, 14)

In [7]:
# Data types and non-null counts

df_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [8]:
# Descriptive statistics
df_dataset.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [9]:
df_dataset.sample(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
858,ORD200858,2023-08-20,C22167,Tablet,5,435.66,891 Main St,Online,Pending,TRK70269748,9,NaN,Facebook,2178.30
701,ORD200701,2024-06-23,C75456,Monitor,3,92.22,115 Main St,Credit Card,Delivered,TRK90519490,5,FREESHIP,Email,276.66
908,ORD200908,2025-05-06,C35117,Desk,2,697.93,332 Main St,Credit Card,Cancelled,TRK27155709,2,SAVE10,Google,1395.86
612,ORD200612,2023-06-02,C51811,Chair,3,445.12,339 Main St,Gift Card,Cancelled,TRK82377939,8,NaN,Google,1335.36
997,ORD200997,2023-11-27,C26210,Laptop,3,444.75,805 Main St,Cash,Delivered,TRK40616861,6,SAVE10,Facebook,1334.25
686,ORD200686,2023-10-09,C41903,Desk,3,53.60,525 Main St,Cash,Pending,TRK59112382,4,WINTER15,Facebook,160.80
1160,ORD201160,2024-09-04,C40466,Desk,1,541.64,449 Main St,Debit Card,Shipped,TRK70255168,5,SAVE10,Email,541.64
1159,ORD201159,2024-02-23,C66112,Desk,4,466.70,874 Main St,Debit Card,Returned,TRK60955607,8,NaN,Instagram,1866.80
854,ORD200854,2025-06-13,C56938,Laptop,3,372.60,356 Main St,Credit Card,Delivered,TRK67735987,7,WINTER15,Referral,1117.80
944,ORD200944,2024-12-16,C32687,Laptop,2,426.22,448 Main St,Online,Delivered,TRK98284560,7,WINTER15,Google,852.44

In [10]:
# Check datatypes
df_dataset.dtypes

OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

## Step 3: Cleaning

In [11]:
# Convert Date column to datetime format
df_dataset['Date'] = pd.to_datetime(df_dataset['Date'])

In [12]:
df_dataset['Year'] = df_dataset['Date'].dt.year
df_dataset['Month'] = df_dataset['Date'].dt.month
df_dataset.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72,2023,10
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42,2025,6
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75,2023,5
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56,2025,4
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52,2023,11

In [13]:
# Missing values percentage
missing_percentage = df_dataset.isnull().sum() / len(df_dataset) * 100
print(missing_percentage)

OrderID             0.00
Date                0.00
CustomerID          0.00
Product             0.00
Quantity            0.00
UnitPrice           0.00
ShippingAddress     0.00
PaymentMethod       0.00
OrderStatus         0.00
TrackingNumber      0.00
ItemsInCart         0.00
CouponCode         25.75
ReferralSource      0.00
TotalPrice          0.00
Year                0.00
Month               0.00
dtype: float64

In [14]:
# fill missing values in Couponcode column with 'no_coupon'
df_dataset['CouponCode'] = df_dataset['CouponCode'].fillna('no_coupon')
df_dataset['CouponCode'].value_counts()

# fill missing values in CustomerID column with 'Unknown'
df_dataset['CustomerID'] = df_dataset['CustomerID'].fillna('Unknown')
df_dataset['CustomerID'].value_counts()

df_dataset.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72,2023,10
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42,2025,6
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75,2023,5
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,no_coupon,Email,268.56,2025,4
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52,2023,11

In [15]:
# check duplicates
df_dataset.duplicated().sum()

# if there are duplicates, drop them
df_dataset.drop_duplicates(inplace = True)

In [16]:
# check unique OrderIDs
df_dataset['OrderID'].nunique()

1200

In [17]:
# Calculate the expected total price (Quantity × UnitPrice)
df_dataset['Calculated_Total'] = df_dataset['Quantity'] * df_dataset['UnitPrice']

# Create a True/False column: True if mismatch exists, False if they match
df_dataset['Mismatch'] = (df_dataset['Calculated_Total'] != df_dataset['TotalPrice'])

# Count how many rows have mismatches
df_dataset['Mismatch'].sum()

np.int64(134)

In [18]:
# check if there are still missing values
df_dataset.isnull().sum()

OrderID             0
Date                0
CustomerID          0
Product             0
Quantity            0
UnitPrice           0
ShippingAddress     0
PaymentMethod       0
OrderStatus         0
TrackingNumber      0
ItemsInCart         0
CouponCode          0
ReferralSource      0
TotalPrice          0
Year                0
Month               0
Calculated_Total    0
Mismatch            0
dtype: int64

In [19]:
#check the final cleaned dataset
df_dataset.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Calculated_Total,Mismatch
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2023,1,2853.10,False
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,2024,8,302.70,False
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2024,2,2753.40,True
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,2023,10,273.19,False
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2025,5,2504.04,False
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72,2023,10,491.72,False
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42,2025,6,664.42,False
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75,2023,5,747.75,False
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,no_coupon,Email,268.56,2025,4,268.56,False
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52,2023,11,2037.52,False

In [20]:
# standardize PaymentMethod values
df_dataset['PaymentMethod'] =(
    df_dataset['PaymentMethod'].str.lower().str.strip()
)

In [21]:
df_dataset.to_csv('Dataset/cleaned_dataset.csv', index = False)